services:
  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: hype-monitor-redis
    ports:
      - "${REDIS_PORT:-6380}:6379"  # 默认使用6380端口避免冲突
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - hype-monitor-network

  # HYPE监控服务
  hype-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hype-monitor-app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: production
      # WebSocket连接稳定配置
      HYPERLIQUID_WS_URL: "${HYPERLIQUID_WS_URL:-wss://api.hyperliquid.xyz/ws}"
      HYPERLIQUID_RECONNECT_ATTEMPTS: "${HYPERLIQUID_RECONNECT_ATTEMPTS:-3}"
      CONNECTION_TIMEOUT: "${CONNECTION_TIMEOUT:-60000}"
      SUBSCRIPTION_TIMEOUT: "${SUBSCRIPTION_TIMEOUT:-45000}"
      CONNECTION_DELAY: "${CONNECTION_DELAY:-20000}"
      KEEP_ALIVE_INTERVAL: "${KEEP_ALIVE_INTERVAL:-35000}"
      KEEP_ALIVE_TIMEOUT: "${KEEP_ALIVE_TIMEOUT:-30000}"
      MAX_CONSECUTIVE_ERRORS: "${MAX_CONSECUTIVE_ERRORS:-15}"
      MAX_RECONNECT_ATTEMPTS: "${MAX_RECONNECT_ATTEMPTS:-3}"
      # Redis配置
      REDIS_URL: redis://redis:6379
      REDIS_KEY_PREFIX: "hype_monitor:"
      # Webhook配置
      WEBHOOK_URL: "${WEBHOOK_URL:-https://httpbin.org/post}"
      CONTRACT_WEBHOOK_URL: "${CONTRACT_WEBHOOK_URL:-https://httpbin.org/post}"
      WEBHOOK_TIMEOUT: "${WEBHOOK_TIMEOUT:-10000}"
      WEBHOOK_RETRIES: "${WEBHOOK_RETRIES:-5}"
      # 监控阈值配置
      SINGLE_TRANSFER_THRESHOLD: "${SINGLE_TRANSFER_THRESHOLD:-10000}"
      CUMULATIVE_24H_THRESHOLD: "${CUMULATIVE_24H_THRESHOLD:-50000}"
      # 合约监控配置
      CONTRACT_MONITORING_ENABLED: "${CONTRACT_MONITORING_ENABLED:-true}"
      CONTRACT_MIN_NOTIONAL: "${CONTRACT_MIN_NOTIONAL:-10}"
      CONTRACT_ASSETS: "${CONTRACT_ASSETS:-BTC,ETH,SOL}"
      # 日志配置
      LOG_LEVEL: "${LOG_LEVEL:-debug}"
      LOG_FILE: "logs/hype-monitor.log"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "process.exit(0)"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
    networks:
      - hype-monitor-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # 开发服务（可选）
  hype-monitor-dev:
    build:
      context: .
      dockerfile: Dockerfile.multistage
      target: development
    container_name: hype-monitor-dev
    depends_on:
      redis:
        condition: service_healthy
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      REDIS_KEY_PREFIX: "hype_monitor_dev:"
      LOG_LEVEL: debug
      WEBHOOK_URL: "${WEBHOOK_URL:-https://httpbin.org/post}"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - hype-monitor-network
    profiles:
      - dev

volumes:
  redis_data:
    driver: local

networks:
  hype-monitor-network:
    driver: bridge
